controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    xavbot_controller:
      type: mecanum_drive_controller/MecanumDriveController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController    

xavbot_controller:
  ros__parameters:
    fl_name: "front_left_wheel_joint"
    fr_name: "front_right_wheel_joint"
    rl_name: "rear_left_wheel_joint"
    rr_name: "rear_right_wheel_joint"
    wheel_radius: 0.0175
    wheelbase_width: 0.274
    wheelbase_length: 0.188

velocity_controller:
  ros__parameters:
    joints:
      - link1_joint
      - link2_joint
      - link3_joint
      - link4_joint
      # - gripper

joint_trajectory_controller:
  ros__parameters:
    joints:
      - link1_joint
      - link2_joint
      - link3_joint
      - link4_joint
      # - gripper

    command_interfaces:
      - position

    state_interfaces:
      - position
