# Used by the xavbot_perception/AprilTagManager server. 
# Returns the most recent detection of each tag specified in the tag_ids field.
# Any tag_ids which have never been detected are returned in the failed_tags field.

# Request
int32[] tag_ids
---
# Result
AprilTagDetectionStamped[] detections
int32[] failed_tags
---
# Feedback